
# TDAMERITRADE specific variables
CLIENT_ID = os.getenv('TDAMERITRADE_CLIENT_ID')
ACCOUNT_ID = os.getenv('TDAMERITRADE_ACCOUNT_ID')
REFRESH_TOKEN = os.getenv('TDAMERITRADE_REFRESH_TOKEN')

# Alpha Vantage API
VANTAGE_API_KEY = "1234"
